# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your title here
email: your@email.com
description: > # this means to ignore newlines until "baseurl:"
  Your description here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your.url.here" # the base hostname & protocol for your site
facebook_username: facebook_user
instagram_username: instagram_user
twitter_username: twitter_user
github_username: github_user

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

color: gray
lang: en
taggs: "tags, here"

exclude: ['package.json', 'dev', 'node_modules', 'screenshots', 'gulpfile.js', 'back*.*']

sass:
  sass_dir: dev/scss